/**
 * The truss extension for pi (issue #203). pi has no MCP surface — its tool
 * model is extensions — so the feed was unreachable from pi sessions. This
 * ships a generated extension (~/.pi/agent/extensions/truss.ts, installed by
 * pi-config.ts) that registers post_feed / list_feed as native pi tools and
 * bridges them onto the truss server's MCP HTTP endpoint.
 *
 * The generated source reads two env vars the pi adapter exports at spawn:
 * TRUSS_SESSION_ID (posts are attributed to the calling session — the MCP
 * route scopes by URL) and TRUSS_MCP_BASE (only when the server isn't the
 * loopback default, e.g. a remote node-agent pointed back at its server).
 */

export function piTrussExtensionSource(): string {
  return `/**
 * truss feed tools for pi — GENERATED by the truss server (pi-config.ts);
 * edits here are overwritten on the next sync. pi speaks extensions, not
 * MCP, so post_feed / list_feed are bridged onto the truss server's MCP
 * HTTP endpoint (issue #203).
 */
import { Type } from "@earendil-works/pi-ai";
import { defineTool, type ExtensionAPI } from "@earendil-works/pi-coding-agent";

const BASE = (process.env.TRUSS_MCP_BASE ?? "http://127.0.0.1:4040").replace(/\\/+$/, "");
const SESSION = process.env.TRUSS_SESSION_ID ?? "";

async function callTruss(tool: string, args: Record<string, unknown>, signal?: AbortSignal): Promise<string> {
  if (!SESSION) {
    throw new Error("TRUSS_SESSION_ID is not set — this pi process was not spawned by truss");
  }
  const res = await fetch(BASE + "/mcp/truss/" + encodeURIComponent(SESSION), {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      jsonrpc: "2.0",
      id: 1,
      method: "tools/call",
      params: { name: tool, arguments: args },
    }),
    signal,
  });
  if (!res.ok) throw new Error("truss " + tool + " failed: HTTP " + res.status);
  const rpc = (await res.json()) as {
    error?: { message?: string };
    result?: { content?: { type: string; text?: string }[]; isError?: boolean };
  };
  if (rpc.error) throw new Error("truss " + tool + " failed: " + (rpc.error.message ?? "unknown error"));
  const text = (rpc.result?.content ?? []).map((c) => c.text ?? "").join("\\n");
  if (rpc.result?.isError) throw new Error(text || "truss " + tool + " failed");
  return text;
}

const postFeed = defineTool({
  name: "post_feed",
  label: "Post to feed",
  description:
    "Post a card to the user's feed (their inbox). Use type 'report' for finished research/analysis, " +
    "'note' for heads-ups. Keep titles one line; put the substance in the markdown body.",
  promptSnippet: "post reports and heads-ups to the user's feed",
  parameters: Type.Object({
    type: Type.Optional(
      Type.Union([Type.Literal("report"), Type.Literal("note")], {
        description: "report = finished work (default), note = heads-up",
      }),
    ),
    title: Type.String({ description: "one-line title" }),
    body: Type.Optional(Type.String({ description: "markdown body — the substance" })),
    importance: Type.Optional(
      Type.Union([Type.Literal("low"), Type.Literal("normal"), Type.Literal("high"), Type.Literal("urgent")]),
    ),
  }),
  async execute(_toolCallId, params, signal) {
    const text = await callTruss("post_feed", params as Record<string, unknown>, signal);
    return { content: [{ type: "text", text }], details: undefined };
  },
});

const listFeed = defineTool({
  name: "list_feed",
  label: "List feed",
  description: "List the feed cards the user has shared to this session.",
  promptSnippet: "read feed cards shared to you",
  parameters: Type.Object({}),
  async execute(_toolCallId, _params, signal) {
    const text = await callTruss("list_feed", {}, signal);
    return { content: [{ type: "text", text: text || "(no cards shared to this session)" }], details: undefined };
  },
});

export default function (pi: ExtensionAPI) {
  pi.registerTool(postFeed);
  pi.registerTool(listFeed);
}
`;
}
